"""initial migration

Revision ID: 2471e3ccb72c
Revises: 
Create Date: 2025-03-26 15:55:50.214828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2471e3ccb72c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remitosproductos',
    sa.Column('id_remito', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.ForeignKeyConstraint(['id_remito'], ['remitos.id_remito'], ),
    sa.PrimaryKeyConstraint('id_remito', 'id_producto')
    )
    op.drop_table('remitos_productos')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('precio',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('id_proveedor',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('stock',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('imagen',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('categoria',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_constraint('productos_id_proveedor_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'proveedores', ['id_proveedor'], ['id_proveedor'])

    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.alter_column('direccion',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('fecha_registro',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('proveedores_email_key', type_='unique')

    with op.batch_alter_table('remitos', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
        batch_op.alter_column('id_sucursal',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('id_empleado',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pendiente'::character varying"))
        batch_op.alter_column('id_sucursal_origen',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('id_sucursal_destino',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('idx_remitos_fecha')
        batch_op.drop_constraint('remitos_id_empleado_fkey', type_='foreignkey')
        batch_op.drop_constraint('remitos_id_sucursal_fkey', type_='foreignkey')
        batch_op.drop_constraint('remitos_id_sucursal_origen_fkey', type_='foreignkey')
        batch_op.drop_constraint('remitos_id_sucursal_destino_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'sucursales', ['id_sucursal_destino'], ['id_sucursal'])
        batch_op.create_foreign_key(None, 'sucursales', ['id_sucursal'], ['id_sucursal'])
        batch_op.create_foreign_key(None, 'sucursales', ['id_sucursal_origen'], ['id_sucursal'])
        batch_op.create_foreign_key(None, 'usuarios', ['id_empleado'], ['id_usuario'])

    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.alter_column('direccion',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('ciudad',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('codigo_postal',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('fecha_apertura',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('horario_apertura',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('id_sucursal',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('fecha_ultima_sesion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('rol',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.drop_constraint('usuarios_nombre_usuario_key', type_='unique')
        batch_op.drop_constraint('usuarios_id_sucursal_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'sucursales', ['id_sucursal'], ['id_sucursal'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('usuarios_id_sucursal_fkey', 'sucursales', ['id_sucursal'], ['id_sucursal'], ondelete='SET NULL')
        batch_op.create_unique_constraint('usuarios_nombre_usuario_key', ['nombre_usuario'])
        batch_op.alter_column('rol',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('fecha_ultima_sesion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('id_sucursal',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('horario_apertura',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('fecha_apertura',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('codigo_postal',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('ciudad',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('direccion',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('remitos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('remitos_id_sucursal_destino_fkey', 'sucursales', ['id_sucursal_destino'], ['id_sucursal'], ondelete='SET NULL')
        batch_op.create_foreign_key('remitos_id_sucursal_origen_fkey', 'sucursales', ['id_sucursal_origen'], ['id_sucursal'], ondelete='SET NULL')
        batch_op.create_foreign_key('remitos_id_sucursal_fkey', 'sucursales', ['id_sucursal'], ['id_sucursal'], ondelete='SET NULL')
        batch_op.create_foreign_key('remitos_id_empleado_fkey', 'usuarios', ['id_empleado'], ['id_usuario'], ondelete='SET NULL')
        batch_op.create_index('idx_remitos_fecha', ['fecha'], unique=False)
        batch_op.alter_column('id_sucursal_destino',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_sucursal_origen',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pendiente'::character varying"))
        batch_op.alter_column('id_empleado',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_sucursal',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))

    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.create_unique_constraint('proveedores_email_key', ['email'])
        batch_op.alter_column('fecha_registro',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('direccion',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('productos_id_proveedor_fkey', 'proveedores', ['id_proveedor'], ['id_proveedor'], ondelete='SET NULL')
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('categoria',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('imagen',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('stock',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('id_proveedor',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('precio',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('descripcion',
               existing_type=sa.TEXT(),
               nullable=True)

    op.create_table('remitos_productos',
    sa.Column('id_remito', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_producto', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('precio', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.CheckConstraint('cantidad > 0', name='remitos_productos_cantidad_check'),
    sa.CheckConstraint('precio >= 0::numeric', name='remitos_productos_precio_check'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], name='remitos_productos_id_producto_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_remito'], ['remitos.id_remito'], name='remitos_productos_id_remito_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_remito', 'id_producto', name='remitos_productos_pkey')
    )
    op.drop_table('remitosproductos')
    # ### end Alembic commands ###
